### ISSUE TITLE
Cannot download the AirGen in User Portal 

### ISSUE THREAD

**Issue by 1180300611haobowen** [ScaledFoundations/GRID-playground#16]
I have encountered an issue where the download links provided in the User Portal are no longer accessible.
The error message is 'This XML file does not appear to have any style information associated with it.  The document tree is shown below'. 
I don't know if it's due to the website or something else，Is there another way to get it？

**Comment by Nish1no7** [comment]
Same question...

**Comment by saihv** [comment]
Please find the new version of GRID at grid.scaledfoundations.ai - now fully web-based and includes all the old environments and robot capabilities, now enhanced with a full IDE for development.
