### ISSUE TITLE
License

### ISSUE THREAD

**Issue by arthur-x88** [ScaledFoundations/GRID-playground#4]
What is the licensing terms for Airgen for students? Thinking on implementing land vehicles.

**Comment by saihv** [comment]
AirGen is covered by the Scaled Foundations' Responsible AI license the full terms of which can be found at our portal: https://portal.scaledfoundations.ai. AirGen is free to use for academic non-commercial purposes.

Please note that as of now, AirGen only supports drones and an embodied agent. We will be adding support for more form factors soon.
