### ISSUE TITLE
Set up the AI layer (documentation error)

### ISSUE THREAD

**Issue by munirjojoverge** [ScaledFoundations/GRID-playground#5]
On the first step:

```
docker pull scaledfoundations/grid:base
```

```
docker run -it --gpus all --network host grid:base
```

The issue here is the way you guys suggested to be referencing the Docker image. The image is pulled from scaledfoundations/grid:base, but when you run the docker run command, you're only specifying grid:base, which Docker can't find locally or in the default Docker registry.

You should use the full name of the image including the repository when running it:

```
docker run -it --gpus all --network host scaledfoundations/grid:base
```
This will tell Docker to use the scaledfoundations/grid:base image that you've pulled, and it should be able to locate it and run it successfully.

**Comment by saihv** [comment]
Good catch, thanks! Fixed now.
