### ISSUE TITLE
Is it possible to use other LLM, other than GPT-4 or GPT-3.5

### ISSUE THREAD

**Issue by fantasy4everts** [ScaledFoundations/GRID-playground#8]
is It possible to use other LLM in the simulator,  For example, in scaledfoundations grid:base.  Could I modify the config/airgen_config.yml  or somewhere to use other LLM.

**Comment by saihv** [comment]
At the moment we only support GPT variants out of the box, but we're looking into adding support for other LLMs as part of future updates.
